/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OpenCVTest */

#ifndef _Included_edu_carleton_comp4601_finalproject_core_OpenCV
#define _Included_edu_carleton_comp4601_finalproject_core_OpenCV
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     OpenCVTest
     * Method:    faceDetection
     * Signature: (Ljava/lang/String;Ljava/lang/String;)V
     */
    JNIEXPORT void JNICALL Java_edu_carleton_comp4601_finalproject_core_OpenCV_faceDetection
    (JNIEnv *, jobject, jstring, jstring, jstring);
    
    /*
     * Class:     edu_carleton_comp4601_finalproject_core_OpenCV
     * Method:    faceRecognization
     * Signature: (Ljava/lang/String;[Ljava/lang/String;ILjava/lang/String;)Z
     */
    JNIEXPORT jint JNICALL Java_edu_carleton_comp4601_finalproject_core_OpenCV_faceRecognization
    (JNIEnv *, jclass, jstring, jobjectArray, jstring, jint);
    
#ifdef __cplusplus
}
#endif
#endif
